[app]
name = "joe"

[build]
command = "npm install && npm run build"

[deploy]
command = "APP_ENV=local php artisan migrate --no-interaction && APP_ENV=local php artisan db:seed --force --no-interaction && APP_ENV=production php artisan config:cache && php artisan route:cache && php artisan view:cache"

[[command]]
name = "web"
module = "php"
runner = "wasm"

[command.annotations.wasi]
main-args = ["-t", "public", "-S", "0.0.0.0:$PORT"]